// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 连接到主机
Future<void> connect({required HostConfig host, required String deviceToken}) =>
    RustLib.instance.api.crateApiConnect(host: host, deviceToken: deviceToken);

/// 断开连接
Future<void> disconnect() => RustLib.instance.api.crateApiDisconnect();

/// 获取当前连接状态
Future<ConnectionState> connectionState() =>
    RustLib.instance.api.crateApiConnectionState();

/// 获取会话列表
Future<List<SessionSummary>> listSessions() =>
    RustLib.instance.api.crateApiListSessions();

/// 订阅会话更新（返回初始条目列表，后续通过轮询获取）
Future<List<AcpEntry>> subscribeSession({required String sessionId}) =>
    RustLib.instance.api.crateApiSubscribeSession(sessionId: sessionId);

/// 获取会话新条目（轮询用）
Future<List<AcpEntry>> pollSessionEntries({
  required String sessionId,
  required int sinceIndex,
}) => RustLib.instance.api.crateApiPollSessionEntries(
  sessionId: sessionId,
  sinceIndex: sinceIndex,
);

/// 发送用户消息
Future<void> sendMessage({required String sessionId, required String text}) =>
    RustLib.instance.api.crateApiSendMessage(sessionId: sessionId, text: text);

/// 响应审批
Future<void> respondApproval({
  required String sessionId,
  required String optionKey,
  String? customText,
}) => RustLib.instance.api.crateApiRespondApproval(
  sessionId: sessionId,
  optionKey: optionKey,
  customText: customText,
);

/// 获取当前审批菜单
Future<ApprovalMenu?> getApprovalMenu({required String sessionId}) =>
    RustLib.instance.api.crateApiGetApprovalMenu(sessionId: sessionId);

/// 标记会话已读
Future<void> markSessionRead({required String sessionId}) =>
    RustLib.instance.api.crateApiMarkSessionRead(sessionId: sessionId);

/// 生成密钥对（配对时用）
Future<KeyPair> generateKeypair() =>
    RustLib.instance.api.crateApiGenerateKeypair();

/// 解析配对二维码
Future<HostConfig> parsePairingQr({required String qrData}) =>
    RustLib.instance.api.crateApiParsePairingQr(qrData: qrData);

@freezed
sealed class AcpEntry with _$AcpEntry {
  const AcpEntry._();

  /// 用户消息
  const factory AcpEntry.user({required String text}) = AcpEntry_User;

  /// Assistant 回复
  const factory AcpEntry.assistant({
    required String text,
    required bool thought,
  }) = AcpEntry_Assistant;

  /// 工具调用
  const factory AcpEntry.toolCall({
    required String id,
    required String title,
    required ToolKind kind,
    required ToolStatus status,
    required List<String> output,
  }) = AcpEntry_ToolCall;
}

/// Agent 类型
enum AgentKind { claude, codex, copilot, grok, other }

/// 审批类型
enum ApprovalKind { approve, deny, custom }

/// 审批菜单
class ApprovalMenu {
  final String key;
  final String prompt;
  final List<ApprovalOption> options;
  final bool allowsTextInput;

  const ApprovalMenu({
    required this.key,
    required this.prompt,
    required this.options,
    required this.allowsTextInput,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      prompt.hashCode ^
      options.hashCode ^
      allowsTextInput.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApprovalMenu &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          prompt == other.prompt &&
          options == other.options &&
          allowsTextInput == other.allowsTextInput;
}

/// 审批选项
class ApprovalOption {
  final String key;
  final String label;
  final ApprovalKind kind;

  const ApprovalOption({
    required this.key,
    required this.label,
    required this.kind,
  });

  @override
  int get hashCode => key.hashCode ^ label.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApprovalOption &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          kind == other.kind;
}

/// 连接状态
enum ConnectionState {
  disconnected,
  connecting,
  handshaking,
  connected,
  reconnecting,
  authFailed,
}

/// 主机配置（配对后存储）
class HostConfig {
  final String id;
  final String name;
  final String endpoint;
  final String publicKeyB64;

  const HostConfig({
    required this.id,
    required this.name,
    required this.endpoint,
    required this.publicKeyB64,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ endpoint.hashCode ^ publicKeyB64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostConfig &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          endpoint == other.endpoint &&
          publicKeyB64 == other.publicKeyB64;
}

/// 密钥对
class KeyPair {
  final String publicKeyB64;
  final String secretKeyB64;

  const KeyPair({required this.publicKeyB64, required this.secretKeyB64});

  @override
  int get hashCode => publicKeyB64.hashCode ^ secretKeyB64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPair &&
          runtimeType == other.runtimeType &&
          publicKeyB64 == other.publicKeyB64 &&
          secretKeyB64 == other.secretKeyB64;
}

/// 会话状态
enum SessionStatus {
  /// 空闲，等待用户输入
  idle,

  /// Agent 正在运行
  running,

  /// 等待用户审批（权限请求）
  waitingApproval,

  /// 等待用户输入（agent 主动询问）
  waitingInput,

  /// 出错
  error,
}

/// 会话摘要（列表展示用）
class SessionSummary {
  final String id;
  final String title;
  final SessionStatus status;
  final AgentKind agentKind;
  final String? lastMessage;
  final bool unread;
  final PlatformInt64 updatedAt;

  const SessionSummary({
    required this.id,
    required this.title,
    required this.status,
    required this.agentKind,
    this.lastMessage,
    required this.unread,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      status.hashCode ^
      agentKind.hashCode ^
      lastMessage.hashCode ^
      unread.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          status == other.status &&
          agentKind == other.agentKind &&
          lastMessage == other.lastMessage &&
          unread == other.unread &&
          updatedAt == other.updatedAt;
}

/// 工具类型
enum ToolKind { read, write, edit, bash, other }

/// 工具状态
enum ToolStatus { running, completed, failed }
