// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 启动到指定 EndpointId 的 iroh 隧道，返回手机本地入口端口。
///
/// Dart 侧随后照常连 `ws://127.0.0.1:<port>/acp/ws?token=...`：
/// 隧道对上层是透明的，鉴权和消息格式都和直连网关时完全一样。
///
/// 幂等 —— 同一个 endpoint 重复调用返回同一个端口。
Future<int> irohTunnelStart({
  required String endpointId,
  required String relayUrl,
  required String relayToken,
}) => RustLib.instance.api.crateApiIrohIrohTunnelStart(
  endpointId: endpointId,
  relayUrl: relayUrl,
  relayToken: relayToken,
);

/// 停止 iroh 隧道。没有隧道时是 no-op。
Future<void> irohTunnelStop() =>
    RustLib.instance.api.crateApiIrohIrohTunnelStop();

/// 当前隧道的本地端口，没有则返回 `None`。
Future<int?> irohTunnelPort() =>
    RustLib.instance.api.crateApiIrohIrohTunnelPort();

Future<IrohPathStatus?> irohTunnelPathStatus() =>
    RustLib.instance.api.crateApiIrohIrohTunnelPathStatus();

/// 解析 `smelt+iroh://` 配对码。
///
/// Dart 侧自己也有一份解析（`pairing_config.dart`，扫码即时校验用，不能等
/// FFI 起来）。这个函数留给需要在 Rust 侧核对同一个码的场景，两边都以
/// `smelt-core::pairing` 为准。
Future<IrohPairing> parseIrohPairingUri({required String uri}) =>
    RustLib.instance.api.crateApiIrohParseIrohPairingUri(uri: uri);

/// `smelt+iroh://` 配对码的两半。缺一不可：EndpointId 决定连得上谁，
/// token 决定连上之后能不能操作。
class IrohPairing {
  final String endpointId;
  final String token;
  final String relayUrl;
  final String relayToken;

  const IrohPairing({
    required this.endpointId,
    required this.token,
    required this.relayUrl,
    required this.relayToken,
  });

  @override
  int get hashCode =>
      endpointId.hashCode ^
      token.hashCode ^
      relayUrl.hashCode ^
      relayToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IrohPairing &&
          runtimeType == other.runtimeType &&
          endpointId == other.endpointId &&
          token == other.token &&
          relayUrl == other.relayUrl &&
          relayToken == other.relayToken;
}

/// iroh 当前选中的实际传输路径和 QUIC RTT。
class IrohPathStatus {
  /// `lan`、`p2p` 或 `relay`。
  final String kind;
  final int rttMs;

  const IrohPathStatus({required this.kind, required this.rttMs});

  @override
  int get hashCode => kind.hashCode ^ rttMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IrohPathStatus &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          rttMs == other.rttMs;
}
