// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 启动到指定 EndpointId 的 iroh 隧道，返回手机本地入口端口。
///
/// Dart 侧随后照常连 `ws://127.0.0.1:<port>/acp/ws?token=...`：
/// 隧道对上层是透明的，鉴权和消息格式都和直连网关时完全一样。
///
/// 幂等 —— 同一个 endpoint 重复调用返回同一个端口。
Future<int> irohTunnelStart({
  required String endpointId,
  required String relayUrl,
}) => RustLib.instance.api.crateApiIrohIrohTunnelStart(
  endpointId: endpointId,
  relayUrl: relayUrl,
);

/// 停止 iroh 隧道。没有隧道时是 no-op。
Future<void> irohTunnelStop() =>
    RustLib.instance.api.crateApiIrohIrohTunnelStop();

Future<IrohPathStatus?> irohTunnelPathStatus() =>
    RustLib.instance.api.crateApiIrohIrohTunnelPathStatus();

/// iroh 当前选中的实际传输路径和 QUIC RTT。
class IrohPathStatus {
  /// `lan`、`p2p` 或 `relay`。
  final String kind;
  final int rttMs;

  const IrohPathStatus({required this.kind, required this.rttMs});

  @override
  int get hashCode => kind.hashCode ^ rttMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IrohPathStatus &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          rttMs == other.rttMs;
}
