// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 2126967747;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'smelt_mobile',
        ioDirectory: '../crates/smelt-mobile/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiConnect({
    required HostConfig host,
    required String deviceToken,
  });

  Future<ConnectionState> crateApiConnectionState();

  Future<void> crateApiDisconnect();

  Future<KeyPair> crateApiGenerateKeypair();

  Future<ApprovalMenu?> crateApiGetApprovalMenu({required String sessionId});

  Future<void> crateApiInitApp();

  Future<List<SessionSummary>> crateApiListSessions();

  Future<void> crateApiMarkSessionRead({required String sessionId});

  Future<HostConfig> crateApiParsePairingQr({required String qrData});

  Future<List<AcpEntry>> crateApiPollSessionEntries({
    required String sessionId,
    required int sinceIndex,
  });

  Future<void> crateApiRespondApproval({
    required String sessionId,
    required String optionKey,
    String? customText,
  });

  Future<void> crateApiSendMessage({
    required String sessionId,
    required String text,
  });

  Future<List<AcpEntry>> crateApiSubscribeSession({required String sessionId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiConnect({
    required HostConfig host,
    required String deviceToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_box_autoadd_host_config(host);
          var arg1 = cst_encode_String(deviceToken);
          return wire.wire__crate__api__connect(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiConnectConstMeta,
        argValues: [host, deviceToken],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectConstMeta => const TaskConstMeta(
    debugName: "connect",
    argNames: ["host", "deviceToken"],
  );

  @override
  Future<ConnectionState> crateApiConnectionState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__connection_state(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_connection_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConnectionStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionStateConstMeta =>
      const TaskConstMeta(debugName: "connection_state", argNames: []);

  @override
  Future<void> crateApiDisconnect() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__disconnect(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDisconnectConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDisconnectConstMeta =>
      const TaskConstMeta(debugName: "disconnect", argNames: []);

  @override
  Future<KeyPair> crateApiGenerateKeypair() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__generate_keypair(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_key_pair,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenerateKeypairConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateKeypairConstMeta =>
      const TaskConstMeta(debugName: "generate_keypair", argNames: []);

  @override
  Future<ApprovalMenu?> crateApiGetApprovalMenu({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(sessionId);
          return wire.wire__crate__api__get_approval_menu(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_box_autoadd_approval_menu,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiGetApprovalMenuConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetApprovalMenuConstMeta => const TaskConstMeta(
    debugName: "get_approval_menu",
    argNames: ["sessionId"],
  );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__init_app(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<SessionSummary>> crateApiListSessions() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__list_sessions(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_session_summary,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiListSessionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListSessionsConstMeta =>
      const TaskConstMeta(debugName: "list_sessions", argNames: []);

  @override
  Future<void> crateApiMarkSessionRead({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(sessionId);
          return wire.wire__crate__api__mark_session_read(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiMarkSessionReadConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMarkSessionReadConstMeta => const TaskConstMeta(
    debugName: "mark_session_read",
    argNames: ["sessionId"],
  );

  @override
  Future<HostConfig> crateApiParsePairingQr({required String qrData}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(qrData);
          return wire.wire__crate__api__parse_pairing_qr(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_host_config,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiParsePairingQrConstMeta,
        argValues: [qrData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParsePairingQrConstMeta =>
      const TaskConstMeta(debugName: "parse_pairing_qr", argNames: ["qrData"]);

  @override
  Future<List<AcpEntry>> crateApiPollSessionEntries({
    required String sessionId,
    required int sinceIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(sessionId);
          var arg1 = cst_encode_u_32(sinceIndex);
          return wire.wire__crate__api__poll_session_entries(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_acp_entry,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiPollSessionEntriesConstMeta,
        argValues: [sessionId, sinceIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPollSessionEntriesConstMeta => const TaskConstMeta(
    debugName: "poll_session_entries",
    argNames: ["sessionId", "sinceIndex"],
  );

  @override
  Future<void> crateApiRespondApproval({
    required String sessionId,
    required String optionKey,
    String? customText,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(sessionId);
          var arg1 = cst_encode_String(optionKey);
          var arg2 = cst_encode_opt_String(customText);
          return wire.wire__crate__api__respond_approval(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiRespondApprovalConstMeta,
        argValues: [sessionId, optionKey, customText],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRespondApprovalConstMeta => const TaskConstMeta(
    debugName: "respond_approval",
    argNames: ["sessionId", "optionKey", "customText"],
  );

  @override
  Future<void> crateApiSendMessage({
    required String sessionId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(sessionId);
          var arg1 = cst_encode_String(text);
          return wire.wire__crate__api__send_message(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiSendMessageConstMeta,
        argValues: [sessionId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendMessageConstMeta => const TaskConstMeta(
    debugName: "send_message",
    argNames: ["sessionId", "text"],
  );

  @override
  Future<List<AcpEntry>> crateApiSubscribeSession({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(sessionId);
          return wire.wire__crate__api__subscribe_session(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_acp_entry,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiSubscribeSessionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSubscribeSessionConstMeta => const TaskConstMeta(
    debugName: "subscribe_session",
    argNames: ["sessionId"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AcpEntry dco_decode_acp_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AcpEntry_User(text: dco_decode_String(raw[1]));
      case 1:
        return AcpEntry_Assistant(
          text: dco_decode_String(raw[1]),
          thought: dco_decode_bool(raw[2]),
        );
      case 2:
        return AcpEntry_ToolCall(
          id: dco_decode_String(raw[1]),
          title: dco_decode_String(raw[2]),
          kind: dco_decode_tool_kind(raw[3]),
          status: dco_decode_tool_status(raw[4]),
          output: dco_decode_list_String(raw[5]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  AgentKind dco_decode_agent_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AgentKind.values[raw as int];
  }

  @protected
  ApprovalKind dco_decode_approval_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApprovalKind.values[raw as int];
  }

  @protected
  ApprovalMenu dco_decode_approval_menu(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ApprovalMenu(
      key: dco_decode_String(arr[0]),
      prompt: dco_decode_String(arr[1]),
      options: dco_decode_list_approval_option(arr[2]),
      allowsTextInput: dco_decode_bool(arr[3]),
    );
  }

  @protected
  ApprovalOption dco_decode_approval_option(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApprovalOption(
      key: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      kind: dco_decode_approval_kind(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ApprovalMenu dco_decode_box_autoadd_approval_menu(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_approval_menu(raw);
  }

  @protected
  HostConfig dco_decode_box_autoadd_host_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_host_config(raw);
  }

  @protected
  ConnectionState dco_decode_connection_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConnectionState.values[raw as int];
  }

  @protected
  HostConfig dco_decode_host_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return HostConfig(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      endpoint: dco_decode_String(arr[2]),
      publicKeyB64: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  KeyPair dco_decode_key_pair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return KeyPair(
      publicKeyB64: dco_decode_String(arr[0]),
      secretKeyB64: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AcpEntry> dco_decode_list_acp_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_acp_entry).toList();
  }

  @protected
  List<ApprovalOption> dco_decode_list_approval_option(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_approval_option).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SessionSummary> dco_decode_list_session_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_session_summary).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ApprovalMenu? dco_decode_opt_box_autoadd_approval_menu(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_approval_menu(raw);
  }

  @protected
  SessionStatus dco_decode_session_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SessionStatus.values[raw as int];
  }

  @protected
  SessionSummary dco_decode_session_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SessionSummary(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      status: dco_decode_session_status(arr[2]),
      agentKind: dco_decode_agent_kind(arr[3]),
      lastMessage: dco_decode_opt_String(arr[4]),
      unread: dco_decode_bool(arr[5]),
      updatedAt: dco_decode_i_64(arr[6]),
    );
  }

  @protected
  ToolKind dco_decode_tool_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ToolKind.values[raw as int];
  }

  @protected
  ToolStatus dco_decode_tool_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ToolStatus.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AcpEntry sse_decode_acp_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_text = sse_decode_String(deserializer);
        return AcpEntry_User(text: var_text);
      case 1:
        var var_text = sse_decode_String(deserializer);
        var var_thought = sse_decode_bool(deserializer);
        return AcpEntry_Assistant(text: var_text, thought: var_thought);
      case 2:
        var var_id = sse_decode_String(deserializer);
        var var_title = sse_decode_String(deserializer);
        var var_kind = sse_decode_tool_kind(deserializer);
        var var_status = sse_decode_tool_status(deserializer);
        var var_output = sse_decode_list_String(deserializer);
        return AcpEntry_ToolCall(
          id: var_id,
          title: var_title,
          kind: var_kind,
          status: var_status,
          output: var_output,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  AgentKind sse_decode_agent_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AgentKind.values[inner];
  }

  @protected
  ApprovalKind sse_decode_approval_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ApprovalKind.values[inner];
  }

  @protected
  ApprovalMenu sse_decode_approval_menu(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_prompt = sse_decode_String(deserializer);
    var var_options = sse_decode_list_approval_option(deserializer);
    var var_allowsTextInput = sse_decode_bool(deserializer);
    return ApprovalMenu(
      key: var_key,
      prompt: var_prompt,
      options: var_options,
      allowsTextInput: var_allowsTextInput,
    );
  }

  @protected
  ApprovalOption sse_decode_approval_option(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_kind = sse_decode_approval_kind(deserializer);
    return ApprovalOption(key: var_key, label: var_label, kind: var_kind);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ApprovalMenu sse_decode_box_autoadd_approval_menu(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_approval_menu(deserializer));
  }

  @protected
  HostConfig sse_decode_box_autoadd_host_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_host_config(deserializer));
  }

  @protected
  ConnectionState sse_decode_connection_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ConnectionState.values[inner];
  }

  @protected
  HostConfig sse_decode_host_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_endpoint = sse_decode_String(deserializer);
    var var_publicKeyB64 = sse_decode_String(deserializer);
    return HostConfig(
      id: var_id,
      name: var_name,
      endpoint: var_endpoint,
      publicKeyB64: var_publicKeyB64,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  KeyPair sse_decode_key_pair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_publicKeyB64 = sse_decode_String(deserializer);
    var var_secretKeyB64 = sse_decode_String(deserializer);
    return KeyPair(
      publicKeyB64: var_publicKeyB64,
      secretKeyB64: var_secretKeyB64,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AcpEntry> sse_decode_list_acp_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AcpEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_acp_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApprovalOption> sse_decode_list_approval_option(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApprovalOption>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_approval_option(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SessionSummary> sse_decode_list_session_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SessionSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_session_summary(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ApprovalMenu? sse_decode_opt_box_autoadd_approval_menu(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_approval_menu(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SessionStatus sse_decode_session_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SessionStatus.values[inner];
  }

  @protected
  SessionSummary sse_decode_session_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_status = sse_decode_session_status(deserializer);
    var var_agentKind = sse_decode_agent_kind(deserializer);
    var var_lastMessage = sse_decode_opt_String(deserializer);
    var var_unread = sse_decode_bool(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return SessionSummary(
      id: var_id,
      title: var_title,
      status: var_status,
      agentKind: var_agentKind,
      lastMessage: var_lastMessage,
      unread: var_unread,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  ToolKind sse_decode_tool_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ToolKind.values[inner];
  }

  @protected
  ToolStatus sse_decode_tool_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ToolStatus.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int cst_encode_agent_kind(AgentKind raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_approval_kind(ApprovalKind raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_connection_state(ConnectionState raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_session_status(SessionStatus raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_tool_kind(ToolKind raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_tool_status(ToolStatus raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_acp_entry(AcpEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AcpEntry_User(text: final text):
        sse_encode_i_32(0, serializer);
        sse_encode_String(text, serializer);
      case AcpEntry_Assistant(text: final text, thought: final thought):
        sse_encode_i_32(1, serializer);
        sse_encode_String(text, serializer);
        sse_encode_bool(thought, serializer);
      case AcpEntry_ToolCall(
        id: final id,
        title: final title,
        kind: final kind,
        status: final status,
        output: final output,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(id, serializer);
        sse_encode_String(title, serializer);
        sse_encode_tool_kind(kind, serializer);
        sse_encode_tool_status(status, serializer);
        sse_encode_list_String(output, serializer);
    }
  }

  @protected
  void sse_encode_agent_kind(AgentKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_approval_kind(ApprovalKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_approval_menu(ApprovalMenu self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.prompt, serializer);
    sse_encode_list_approval_option(self.options, serializer);
    sse_encode_bool(self.allowsTextInput, serializer);
  }

  @protected
  void sse_encode_approval_option(
    ApprovalOption self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_approval_kind(self.kind, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_approval_menu(
    ApprovalMenu self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_approval_menu(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_host_config(
    HostConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_host_config(self, serializer);
  }

  @protected
  void sse_encode_connection_state(
    ConnectionState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_host_config(HostConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.endpoint, serializer);
    sse_encode_String(self.publicKeyB64, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_key_pair(KeyPair self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.publicKeyB64, serializer);
    sse_encode_String(self.secretKeyB64, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_acp_entry(
    List<AcpEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_acp_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_approval_option(
    List<ApprovalOption> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_approval_option(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_session_summary(
    List<SessionSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_session_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_approval_menu(
    ApprovalMenu? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_approval_menu(self, serializer);
    }
  }

  @protected
  void sse_encode_session_status(SessionStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_session_summary(
    SessionSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_session_status(self.status, serializer);
    sse_encode_agent_kind(self.agentKind, serializer);
    sse_encode_opt_String(self.lastMessage, serializer);
    sse_encode_bool(self.unread, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_tool_kind(ToolKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_tool_status(ToolStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
