// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AcpEntry dco_decode_acp_entry(dynamic raw);

  @protected
  AgentKind dco_decode_agent_kind(dynamic raw);

  @protected
  ApprovalKind dco_decode_approval_kind(dynamic raw);

  @protected
  ApprovalMenu dco_decode_approval_menu(dynamic raw);

  @protected
  ApprovalOption dco_decode_approval_option(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ApprovalMenu dco_decode_box_autoadd_approval_menu(dynamic raw);

  @protected
  HostConfig dco_decode_box_autoadd_host_config(dynamic raw);

  @protected
  ConnectionState dco_decode_connection_state(dynamic raw);

  @protected
  HostConfig dco_decode_host_config(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KeyPair dco_decode_key_pair(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AcpEntry> dco_decode_list_acp_entry(dynamic raw);

  @protected
  List<ApprovalOption> dco_decode_list_approval_option(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SessionSummary> dco_decode_list_session_summary(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ApprovalMenu? dco_decode_opt_box_autoadd_approval_menu(dynamic raw);

  @protected
  SessionStatus dco_decode_session_status(dynamic raw);

  @protected
  SessionSummary dco_decode_session_summary(dynamic raw);

  @protected
  ToolKind dco_decode_tool_kind(dynamic raw);

  @protected
  ToolStatus dco_decode_tool_status(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AcpEntry sse_decode_acp_entry(SseDeserializer deserializer);

  @protected
  AgentKind sse_decode_agent_kind(SseDeserializer deserializer);

  @protected
  ApprovalKind sse_decode_approval_kind(SseDeserializer deserializer);

  @protected
  ApprovalMenu sse_decode_approval_menu(SseDeserializer deserializer);

  @protected
  ApprovalOption sse_decode_approval_option(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ApprovalMenu sse_decode_box_autoadd_approval_menu(
    SseDeserializer deserializer,
  );

  @protected
  HostConfig sse_decode_box_autoadd_host_config(SseDeserializer deserializer);

  @protected
  ConnectionState sse_decode_connection_state(SseDeserializer deserializer);

  @protected
  HostConfig sse_decode_host_config(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KeyPair sse_decode_key_pair(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AcpEntry> sse_decode_list_acp_entry(SseDeserializer deserializer);

  @protected
  List<ApprovalOption> sse_decode_list_approval_option(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SessionSummary> sse_decode_list_session_summary(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ApprovalMenu? sse_decode_opt_box_autoadd_approval_menu(
    SseDeserializer deserializer,
  );

  @protected
  SessionStatus sse_decode_session_status(SseDeserializer deserializer);

  @protected
  SessionSummary sse_decode_session_summary(SseDeserializer deserializer);

  @protected
  ToolKind sse_decode_tool_kind(SseDeserializer deserializer);

  @protected
  ToolStatus sse_decode_tool_status(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_approval_menu> cst_encode_box_autoadd_approval_menu(
    ApprovalMenu raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_approval_menu();
    cst_api_fill_to_wire_approval_menu(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_host_config> cst_encode_box_autoadd_host_config(
    HostConfig raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_host_config();
    cst_api_fill_to_wire_host_config(raw, ptr.ref);
    return ptr;
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_acp_entry> cst_encode_list_acp_entry(
    List<AcpEntry> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_acp_entry(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_acp_entry(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_approval_option> cst_encode_list_approval_option(
    List<ApprovalOption> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_approval_option(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_approval_option(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_session_summary> cst_encode_list_session_summary(
    List<SessionSummary> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_session_summary(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_session_summary(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<wire_cst_approval_menu> cst_encode_opt_box_autoadd_approval_menu(
    ApprovalMenu? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_approval_menu(raw);
  }

  @protected
  void cst_api_fill_to_wire_acp_entry(
    AcpEntry apiObj,
    wire_cst_acp_entry wireObj,
  ) {
    if (apiObj is AcpEntry_User) {
      var pre_text = cst_encode_String(apiObj.text);
      wireObj.tag = 0;
      wireObj.kind.User.text = pre_text;
      return;
    }
    if (apiObj is AcpEntry_Assistant) {
      var pre_text = cst_encode_String(apiObj.text);
      var pre_thought = cst_encode_bool(apiObj.thought);
      wireObj.tag = 1;
      wireObj.kind.Assistant.text = pre_text;
      wireObj.kind.Assistant.thought = pre_thought;
      return;
    }
    if (apiObj is AcpEntry_ToolCall) {
      var pre_id = cst_encode_String(apiObj.id);
      var pre_title = cst_encode_String(apiObj.title);
      var pre_kind = cst_encode_tool_kind(apiObj.kind);
      var pre_status = cst_encode_tool_status(apiObj.status);
      var pre_output = cst_encode_list_String(apiObj.output);
      wireObj.tag = 2;
      wireObj.kind.ToolCall.id = pre_id;
      wireObj.kind.ToolCall.title = pre_title;
      wireObj.kind.ToolCall.kind = pre_kind;
      wireObj.kind.ToolCall.status = pre_status;
      wireObj.kind.ToolCall.output = pre_output;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_approval_menu(
    ApprovalMenu apiObj,
    wire_cst_approval_menu wireObj,
  ) {
    wireObj.key = cst_encode_String(apiObj.key);
    wireObj.prompt = cst_encode_String(apiObj.prompt);
    wireObj.options = cst_encode_list_approval_option(apiObj.options);
    wireObj.allows_text_input = cst_encode_bool(apiObj.allowsTextInput);
  }

  @protected
  void cst_api_fill_to_wire_approval_option(
    ApprovalOption apiObj,
    wire_cst_approval_option wireObj,
  ) {
    wireObj.key = cst_encode_String(apiObj.key);
    wireObj.label = cst_encode_String(apiObj.label);
    wireObj.kind = cst_encode_approval_kind(apiObj.kind);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_approval_menu(
    ApprovalMenu apiObj,
    ffi.Pointer<wire_cst_approval_menu> wireObj,
  ) {
    cst_api_fill_to_wire_approval_menu(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_host_config(
    HostConfig apiObj,
    ffi.Pointer<wire_cst_host_config> wireObj,
  ) {
    cst_api_fill_to_wire_host_config(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_host_config(
    HostConfig apiObj,
    wire_cst_host_config wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.endpoint = cst_encode_String(apiObj.endpoint);
    wireObj.public_key_b64 = cst_encode_String(apiObj.publicKeyB64);
  }

  @protected
  void cst_api_fill_to_wire_key_pair(
    KeyPair apiObj,
    wire_cst_key_pair wireObj,
  ) {
    wireObj.public_key_b64 = cst_encode_String(apiObj.publicKeyB64);
    wireObj.secret_key_b64 = cst_encode_String(apiObj.secretKeyB64);
  }

  @protected
  void cst_api_fill_to_wire_session_summary(
    SessionSummary apiObj,
    wire_cst_session_summary wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.title = cst_encode_String(apiObj.title);
    wireObj.status = cst_encode_session_status(apiObj.status);
    wireObj.agent_kind = cst_encode_agent_kind(apiObj.agentKind);
    wireObj.last_message = cst_encode_opt_String(apiObj.lastMessage);
    wireObj.unread = cst_encode_bool(apiObj.unread);
    wireObj.updated_at = cst_encode_i_64(apiObj.updatedAt);
  }

  @protected
  int cst_encode_agent_kind(AgentKind raw);

  @protected
  int cst_encode_approval_kind(ApprovalKind raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_connection_state(ConnectionState raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_session_status(SessionStatus raw);

  @protected
  int cst_encode_tool_kind(ToolKind raw);

  @protected
  int cst_encode_tool_status(ToolStatus raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_acp_entry(AcpEntry self, SseSerializer serializer);

  @protected
  void sse_encode_agent_kind(AgentKind self, SseSerializer serializer);

  @protected
  void sse_encode_approval_kind(ApprovalKind self, SseSerializer serializer);

  @protected
  void sse_encode_approval_menu(ApprovalMenu self, SseSerializer serializer);

  @protected
  void sse_encode_approval_option(
    ApprovalOption self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_approval_menu(
    ApprovalMenu self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_host_config(
    HostConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_state(
    ConnectionState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_host_config(HostConfig self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_key_pair(KeyPair self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_acp_entry(List<AcpEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_approval_option(
    List<ApprovalOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_summary(
    List<SessionSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_approval_menu(
    ApprovalMenu? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_status(SessionStatus self, SseSerializer serializer);

  @protected
  void sse_encode_session_summary(
    SessionSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tool_kind(ToolKind self, SseSerializer serializer);

  @protected
  void sse_encode_tool_status(ToolStatus self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<wire_cst_approval_menu> cst_new_box_autoadd_approval_menu() {
    return _cst_new_box_autoadd_approval_menu();
  }

  late final _cst_new_box_autoadd_approval_menuPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<wire_cst_approval_menu> Function()>
      >('frbgen_smelt_mobile_cst_new_box_autoadd_approval_menu');
  late final _cst_new_box_autoadd_approval_menu =
      _cst_new_box_autoadd_approval_menuPtr
          .asFunction<ffi.Pointer<wire_cst_approval_menu> Function()>();

  ffi.Pointer<wire_cst_host_config> cst_new_box_autoadd_host_config() {
    return _cst_new_box_autoadd_host_config();
  }

  late final _cst_new_box_autoadd_host_configPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_host_config> Function()>>(
        'frbgen_smelt_mobile_cst_new_box_autoadd_host_config',
      );
  late final _cst_new_box_autoadd_host_config =
      _cst_new_box_autoadd_host_configPtr
          .asFunction<ffi.Pointer<wire_cst_host_config> Function()>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(int len) {
    return _cst_new_list_String(len);
  }

  late final _cst_new_list_StringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(ffi.Int32)
        >
      >('frbgen_smelt_mobile_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_acp_entry> cst_new_list_acp_entry(int len) {
    return _cst_new_list_acp_entry(len);
  }

  late final _cst_new_list_acp_entryPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_acp_entry> Function(ffi.Int32)
        >
      >('frbgen_smelt_mobile_cst_new_list_acp_entry');
  late final _cst_new_list_acp_entry = _cst_new_list_acp_entryPtr
      .asFunction<ffi.Pointer<wire_cst_list_acp_entry> Function(int)>();

  ffi.Pointer<wire_cst_list_approval_option> cst_new_list_approval_option(
    int len,
  ) {
    return _cst_new_list_approval_option(len);
  }

  late final _cst_new_list_approval_optionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_approval_option> Function(ffi.Int32)
        >
      >('frbgen_smelt_mobile_cst_new_list_approval_option');
  late final _cst_new_list_approval_option = _cst_new_list_approval_optionPtr
      .asFunction<ffi.Pointer<wire_cst_list_approval_option> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_smelt_mobile_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_session_summary> cst_new_list_session_summary(
    int len,
  ) {
    return _cst_new_list_session_summary(len);
  }

  late final _cst_new_list_session_summaryPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_session_summary> Function(ffi.Int32)
        >
      >('frbgen_smelt_mobile_cst_new_list_session_summary');
  late final _cst_new_list_session_summary = _cst_new_list_session_summaryPtr
      .asFunction<ffi.Pointer<wire_cst_list_session_summary> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__connect(
    int port_,
    ffi.Pointer<wire_cst_host_config> host,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> device_token,
  ) {
    return _wire__crate__api__connect(port_, host, device_token);
  }

  late final _wire__crate__api__connectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_host_config>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_smelt_mobile_wire__crate__api__connect');
  late final _wire__crate__api__connect = _wire__crate__api__connectPtr
      .asFunction<
        void Function(
          int,
          ffi.Pointer<wire_cst_host_config>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  void wire__crate__api__connection_state(int port_) {
    return _wire__crate__api__connection_state(port_);
  }

  late final _wire__crate__api__connection_statePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_smelt_mobile_wire__crate__api__connection_state',
      );
  late final _wire__crate__api__connection_state =
      _wire__crate__api__connection_statePtr.asFunction<void Function(int)>();

  void wire__crate__api__disconnect(int port_) {
    return _wire__crate__api__disconnect(port_);
  }

  late final _wire__crate__api__disconnectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_smelt_mobile_wire__crate__api__disconnect',
      );
  late final _wire__crate__api__disconnect = _wire__crate__api__disconnectPtr
      .asFunction<void Function(int)>();

  void wire__crate__api__generate_keypair(int port_) {
    return _wire__crate__api__generate_keypair(port_);
  }

  late final _wire__crate__api__generate_keypairPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_smelt_mobile_wire__crate__api__generate_keypair',
      );
  late final _wire__crate__api__generate_keypair =
      _wire__crate__api__generate_keypairPtr.asFunction<void Function(int)>();

  void wire__crate__api__get_approval_menu(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> session_id,
  ) {
    return _wire__crate__api__get_approval_menu(port_, session_id);
  }

  late final _wire__crate__api__get_approval_menuPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_smelt_mobile_wire__crate__api__get_approval_menu');
  late final _wire__crate__api__get_approval_menu =
      _wire__crate__api__get_approval_menuPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__init_app(int port_) {
    return _wire__crate__api__init_app(port_);
  }

  late final _wire__crate__api__init_appPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_smelt_mobile_wire__crate__api__init_app',
      );
  late final _wire__crate__api__init_app = _wire__crate__api__init_appPtr
      .asFunction<void Function(int)>();

  void wire__crate__api__list_sessions(int port_) {
    return _wire__crate__api__list_sessions(port_);
  }

  late final _wire__crate__api__list_sessionsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_smelt_mobile_wire__crate__api__list_sessions',
      );
  late final _wire__crate__api__list_sessions =
      _wire__crate__api__list_sessionsPtr.asFunction<void Function(int)>();

  void wire__crate__api__mark_session_read(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> session_id,
  ) {
    return _wire__crate__api__mark_session_read(port_, session_id);
  }

  late final _wire__crate__api__mark_session_readPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_smelt_mobile_wire__crate__api__mark_session_read');
  late final _wire__crate__api__mark_session_read =
      _wire__crate__api__mark_session_readPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__parse_pairing_qr(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> qr_data,
  ) {
    return _wire__crate__api__parse_pairing_qr(port_, qr_data);
  }

  late final _wire__crate__api__parse_pairing_qrPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_smelt_mobile_wire__crate__api__parse_pairing_qr');
  late final _wire__crate__api__parse_pairing_qr =
      _wire__crate__api__parse_pairing_qrPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__poll_session_entries(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> session_id,
    int since_index,
  ) {
    return _wire__crate__api__poll_session_entries(
      port_,
      session_id,
      since_index,
    );
  }

  late final _wire__crate__api__poll_session_entriesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint32,
          )
        >
      >('frbgen_smelt_mobile_wire__crate__api__poll_session_entries');
  late final _wire__crate__api__poll_session_entries =
      _wire__crate__api__poll_session_entriesPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>, int)
          >();

  void wire__crate__api__respond_approval(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> session_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> option_key,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> custom_text,
  ) {
    return _wire__crate__api__respond_approval(
      port_,
      session_id,
      option_key,
      custom_text,
    );
  }

  late final _wire__crate__api__respond_approvalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_smelt_mobile_wire__crate__api__respond_approval');
  late final _wire__crate__api__respond_approval =
      _wire__crate__api__respond_approvalPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__send_message(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> session_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> text,
  ) {
    return _wire__crate__api__send_message(port_, session_id, text);
  }

  late final _wire__crate__api__send_messagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_smelt_mobile_wire__crate__api__send_message');
  late final _wire__crate__api__send_message =
      _wire__crate__api__send_messagePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__subscribe_session(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> session_id,
  ) {
    return _wire__crate__api__subscribe_session(port_, session_id);
  }

  late final _wire__crate__api__subscribe_sessionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_smelt_mobile_wire__crate__api__subscribe_session');
  late final _wire__crate__api__subscribe_session =
      _wire__crate__api__subscribe_sessionPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();
}

final class AcpEntryKind extends ffi.Union {
  external wire_cst_AcpEntry_User User;

  external wire_cst_AcpEntry_Assistant Assistant;

  external wire_cst_AcpEntry_ToolCall ToolCall;
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);

final class wire_cst_AcpEntry_Assistant extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> text;

  @ffi.Bool()
  external bool thought;

  static ffi.Pointer<wire_cst_AcpEntry_Assistant> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> text,
    required bool thought,
  }) => $allocator<wire_cst_AcpEntry_Assistant>()
    ..ref.text = text
    ..ref.thought = thought;
}

final class wire_cst_AcpEntry_ToolCall extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  @ffi.Int32()
  external int kind;

  @ffi.Int32()
  external int status;

  external ffi.Pointer<wire_cst_list_String> output;

  static ffi.Pointer<wire_cst_AcpEntry_ToolCall> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    required int kind,
    required int status,
    required ffi.Pointer<wire_cst_list_String> output,
  }) => $allocator<wire_cst_AcpEntry_ToolCall>()
    ..ref.id = id
    ..ref.title = title
    ..ref.kind = kind
    ..ref.status = status
    ..ref.output = output;
}

final class wire_cst_AcpEntry_User extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> text;

  static ffi.Pointer<wire_cst_AcpEntry_User> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> text,
  }) => $allocator<wire_cst_AcpEntry_User>()..ref.text = text;
}

final class wire_cst_acp_entry extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external AcpEntryKind kind;
}

final class wire_cst_approval_menu extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> key;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> prompt;

  external ffi.Pointer<wire_cst_list_approval_option> options;

  @ffi.Bool()
  external bool allows_text_input;

  static ffi.Pointer<wire_cst_approval_menu> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> key,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> prompt,
    required ffi.Pointer<wire_cst_list_approval_option> options,
    required bool allows_text_input,
  }) => $allocator<wire_cst_approval_menu>()
    ..ref.key = key
    ..ref.prompt = prompt
    ..ref.options = options
    ..ref.allows_text_input = allows_text_input;
}

final class wire_cst_approval_option extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> key;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> label;

  @ffi.Int32()
  external int kind;

  static ffi.Pointer<wire_cst_approval_option> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> key,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> label,
    required int kind,
  }) => $allocator<wire_cst_approval_option>()
    ..ref.key = key
    ..ref.label = label
    ..ref.kind = kind;
}

final class wire_cst_host_config extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> endpoint;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_b64;

  static ffi.Pointer<wire_cst_host_config> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> endpoint,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_b64,
  }) => $allocator<wire_cst_host_config>()
    ..ref.id = id
    ..ref.name = name
    ..ref.endpoint = endpoint
    ..ref.public_key_b64 = public_key_b64;
}

final class wire_cst_key_pair extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_b64;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> secret_key_b64;

  static ffi.Pointer<wire_cst_key_pair> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_b64,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> secret_key_b64,
  }) => $allocator<wire_cst_key_pair>()
    ..ref.public_key_b64 = public_key_b64
    ..ref.secret_key_b64 = secret_key_b64;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_String> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr,
    required int len,
  }) => $allocator<wire_cst_list_String>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_acp_entry extends ffi.Struct {
  external ffi.Pointer<wire_cst_acp_entry> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_acp_entry> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_acp_entry> ptr,
    required int len,
  }) => $allocator<wire_cst_list_acp_entry>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_approval_option extends ffi.Struct {
  external ffi.Pointer<wire_cst_approval_option> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_approval_option> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_approval_option> ptr,
    required int len,
  }) => $allocator<wire_cst_list_approval_option>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_prim_u_8_strict> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Uint8> ptr,
    required int len,
  }) => $allocator<wire_cst_list_prim_u_8_strict>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_session_summary extends ffi.Struct {
  external ffi.Pointer<wire_cst_session_summary> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_session_summary> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_session_summary> ptr,
    required int len,
  }) => $allocator<wire_cst_list_session_summary>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_session_summary extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  @ffi.Int32()
  external int status;

  @ffi.Int32()
  external int agent_kind;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> last_message;

  @ffi.Bool()
  external bool unread;

  @ffi.Int64()
  external int updated_at;

  static ffi.Pointer<wire_cst_session_summary> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    required int status,
    required int agent_kind,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> last_message,
    required bool unread,
    required int updated_at,
  }) => $allocator<wire_cst_session_summary>()
    ..ref.id = id
    ..ref.title = title
    ..ref.status = status
    ..ref.agent_kind = agent_kind
    ..ref.last_message = last_message
    ..ref.unread = unread
    ..ref.updated_at = updated_at;
}
