// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AcpEntry dco_decode_acp_entry(dynamic raw);

  @protected
  AgentKind dco_decode_agent_kind(dynamic raw);

  @protected
  ApprovalKind dco_decode_approval_kind(dynamic raw);

  @protected
  ApprovalMenu dco_decode_approval_menu(dynamic raw);

  @protected
  ApprovalOption dco_decode_approval_option(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ApprovalMenu dco_decode_box_autoadd_approval_menu(dynamic raw);

  @protected
  HostConfig dco_decode_box_autoadd_host_config(dynamic raw);

  @protected
  ConnectionState dco_decode_connection_state(dynamic raw);

  @protected
  HostConfig dco_decode_host_config(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KeyPair dco_decode_key_pair(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AcpEntry> dco_decode_list_acp_entry(dynamic raw);

  @protected
  List<ApprovalOption> dco_decode_list_approval_option(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SessionSummary> dco_decode_list_session_summary(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ApprovalMenu? dco_decode_opt_box_autoadd_approval_menu(dynamic raw);

  @protected
  SessionStatus dco_decode_session_status(dynamic raw);

  @protected
  SessionSummary dco_decode_session_summary(dynamic raw);

  @protected
  ToolKind dco_decode_tool_kind(dynamic raw);

  @protected
  ToolStatus dco_decode_tool_status(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AcpEntry sse_decode_acp_entry(SseDeserializer deserializer);

  @protected
  AgentKind sse_decode_agent_kind(SseDeserializer deserializer);

  @protected
  ApprovalKind sse_decode_approval_kind(SseDeserializer deserializer);

  @protected
  ApprovalMenu sse_decode_approval_menu(SseDeserializer deserializer);

  @protected
  ApprovalOption sse_decode_approval_option(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ApprovalMenu sse_decode_box_autoadd_approval_menu(
    SseDeserializer deserializer,
  );

  @protected
  HostConfig sse_decode_box_autoadd_host_config(SseDeserializer deserializer);

  @protected
  ConnectionState sse_decode_connection_state(SseDeserializer deserializer);

  @protected
  HostConfig sse_decode_host_config(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KeyPair sse_decode_key_pair(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AcpEntry> sse_decode_list_acp_entry(SseDeserializer deserializer);

  @protected
  List<ApprovalOption> sse_decode_list_approval_option(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SessionSummary> sse_decode_list_session_summary(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ApprovalMenu? sse_decode_opt_box_autoadd_approval_menu(
    SseDeserializer deserializer,
  );

  @protected
  SessionStatus sse_decode_session_status(SseDeserializer deserializer);

  @protected
  SessionSummary sse_decode_session_summary(SseDeserializer deserializer);

  @protected
  ToolKind sse_decode_tool_kind(SseDeserializer deserializer);

  @protected
  ToolStatus sse_decode_tool_status(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_acp_entry(AcpEntry raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is AcpEntry_User) {
      return [0, cst_encode_String(raw.text)].jsify()!;
    }
    if (raw is AcpEntry_Assistant) {
      return [
        1,
        cst_encode_String(raw.text),
        cst_encode_bool(raw.thought),
      ].jsify()!;
    }
    if (raw is AcpEntry_ToolCall) {
      return [
        2,
        cst_encode_String(raw.id),
        cst_encode_String(raw.title),
        cst_encode_tool_kind(raw.kind),
        cst_encode_tool_status(raw.status),
        cst_encode_list_String(raw.output),
      ].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny cst_encode_approval_menu(ApprovalMenu raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.key),
      cst_encode_String(raw.prompt),
      cst_encode_list_approval_option(raw.options),
      cst_encode_bool(raw.allowsTextInput),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_approval_option(ApprovalOption raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.key),
      cst_encode_String(raw.label),
      cst_encode_approval_kind(raw.kind),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_box_autoadd_approval_menu(ApprovalMenu raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_approval_menu(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_host_config(HostConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_host_config(raw);
  }

  @protected
  JSAny cst_encode_host_config(HostConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.name),
      cst_encode_String(raw.endpoint),
      cst_encode_String(raw.publicKeyB64),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_key_pair(KeyPair raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.publicKeyB64),
      cst_encode_String(raw.secretKeyB64),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_acp_entry(List<AcpEntry> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_acp_entry).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_approval_option(List<ApprovalOption> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_approval_option).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_session_summary(List<SessionSummary> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_session_summary).toList().jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_approval_menu(ApprovalMenu? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_approval_menu(raw);
  }

  @protected
  JSAny cst_encode_session_summary(SessionSummary raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.title),
      cst_encode_session_status(raw.status),
      cst_encode_agent_kind(raw.agentKind),
      cst_encode_opt_String(raw.lastMessage),
      cst_encode_bool(raw.unread),
      cst_encode_i_64(raw.updatedAt),
    ].jsify()!;
  }

  @protected
  int cst_encode_agent_kind(AgentKind raw);

  @protected
  int cst_encode_approval_kind(ApprovalKind raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_connection_state(ConnectionState raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_session_status(SessionStatus raw);

  @protected
  int cst_encode_tool_kind(ToolKind raw);

  @protected
  int cst_encode_tool_status(ToolStatus raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_acp_entry(AcpEntry self, SseSerializer serializer);

  @protected
  void sse_encode_agent_kind(AgentKind self, SseSerializer serializer);

  @protected
  void sse_encode_approval_kind(ApprovalKind self, SseSerializer serializer);

  @protected
  void sse_encode_approval_menu(ApprovalMenu self, SseSerializer serializer);

  @protected
  void sse_encode_approval_option(
    ApprovalOption self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_approval_menu(
    ApprovalMenu self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_host_config(
    HostConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_state(
    ConnectionState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_host_config(HostConfig self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_key_pair(KeyPair self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_acp_entry(List<AcpEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_approval_option(
    List<ApprovalOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_summary(
    List<SessionSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_approval_menu(
    ApprovalMenu? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_status(SessionStatus self, SseSerializer serializer);

  @protected
  void sse_encode_session_summary(
    SessionSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tool_kind(ToolKind self, SseSerializer serializer);

  @protected
  void sse_encode_tool_status(ToolStatus self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__connect(
    NativePortType port_,
    JSAny host,
    String device_token,
  ) => wasmModule.wire__crate__api__connect(port_, host, device_token);

  void wire__crate__api__connection_state(NativePortType port_) =>
      wasmModule.wire__crate__api__connection_state(port_);

  void wire__crate__api__disconnect(NativePortType port_) =>
      wasmModule.wire__crate__api__disconnect(port_);

  void wire__crate__api__generate_keypair(NativePortType port_) =>
      wasmModule.wire__crate__api__generate_keypair(port_);

  void wire__crate__api__get_approval_menu(
    NativePortType port_,
    String session_id,
  ) => wasmModule.wire__crate__api__get_approval_menu(port_, session_id);

  void wire__crate__api__init_app(NativePortType port_) =>
      wasmModule.wire__crate__api__init_app(port_);

  void wire__crate__api__list_sessions(NativePortType port_) =>
      wasmModule.wire__crate__api__list_sessions(port_);

  void wire__crate__api__mark_session_read(
    NativePortType port_,
    String session_id,
  ) => wasmModule.wire__crate__api__mark_session_read(port_, session_id);

  void wire__crate__api__parse_pairing_qr(
    NativePortType port_,
    String qr_data,
  ) => wasmModule.wire__crate__api__parse_pairing_qr(port_, qr_data);

  void wire__crate__api__poll_session_entries(
    NativePortType port_,
    String session_id,
    int since_index,
  ) => wasmModule.wire__crate__api__poll_session_entries(
    port_,
    session_id,
    since_index,
  );

  void wire__crate__api__respond_approval(
    NativePortType port_,
    String session_id,
    String option_key,
    String? custom_text,
  ) => wasmModule.wire__crate__api__respond_approval(
    port_,
    session_id,
    option_key,
    custom_text,
  );

  void wire__crate__api__send_message(
    NativePortType port_,
    String session_id,
    String text,
  ) => wasmModule.wire__crate__api__send_message(port_, session_id, text);

  void wire__crate__api__subscribe_session(
    NativePortType port_,
    String session_id,
  ) => wasmModule.wire__crate__api__subscribe_session(port_, session_id);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__connect(
    NativePortType port_,
    JSAny host,
    String device_token,
  );

  external void wire__crate__api__connection_state(NativePortType port_);

  external void wire__crate__api__disconnect(NativePortType port_);

  external void wire__crate__api__generate_keypair(NativePortType port_);

  external void wire__crate__api__get_approval_menu(
    NativePortType port_,
    String session_id,
  );

  external void wire__crate__api__init_app(NativePortType port_);

  external void wire__crate__api__list_sessions(NativePortType port_);

  external void wire__crate__api__mark_session_read(
    NativePortType port_,
    String session_id,
  );

  external void wire__crate__api__parse_pairing_qr(
    NativePortType port_,
    String qr_data,
  );

  external void wire__crate__api__poll_session_entries(
    NativePortType port_,
    String session_id,
    int since_index,
  );

  external void wire__crate__api__respond_approval(
    NativePortType port_,
    String session_id,
    String option_key,
    String? custom_text,
  );

  external void wire__crate__api__send_message(
    NativePortType port_,
    String session_id,
    String text,
  );

  external void wire__crate__api__subscribe_session(
    NativePortType port_,
    String session_id,
  );
}
