// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api_iroh.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  IrohPathStatus dco_decode_box_autoadd_iroh_path_status(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  IrohPairing dco_decode_iroh_pairing(dynamic raw);

  @protected
  IrohPathStatus dco_decode_iroh_path_status(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  IrohPathStatus? dco_decode_opt_box_autoadd_iroh_path_status(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  IrohPathStatus sse_decode_box_autoadd_iroh_path_status(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  IrohPairing sse_decode_iroh_pairing(SseDeserializer deserializer);

  @protected
  IrohPathStatus sse_decode_iroh_path_status(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  IrohPathStatus? sse_decode_opt_box_autoadd_iroh_path_status(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_box_autoadd_iroh_path_status(IrohPathStatus raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_iroh_path_status(raw);
  }

  @protected
  int cst_encode_box_autoadd_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_32(raw);
  }

  @protected
  JSAny cst_encode_iroh_pairing(IrohPairing raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.endpointId),
      cst_encode_String(raw.token),
      cst_encode_String(raw.relayUrl),
      cst_encode_String(raw.relayToken),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_iroh_path_status(IrohPathStatus raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.kind), cst_encode_u_32(raw.rttMs)].jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_iroh_path_status(IrohPathStatus? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_iroh_path_status(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_u_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_32(raw);
  }

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_iroh_path_status(
    IrohPathStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_iroh_pairing(IrohPairing self, SseSerializer serializer);

  @protected
  void sse_encode_iroh_path_status(
    IrohPathStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_iroh_path_status(
    IrohPathStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api_iroh__init_app(NativePortType port_) =>
      wasmModule.wire__crate__api_iroh__init_app(port_);

  void wire__crate__api_iroh__iroh_tunnel_path_status(NativePortType port_) =>
      wasmModule.wire__crate__api_iroh__iroh_tunnel_path_status(port_);

  void wire__crate__api_iroh__iroh_tunnel_port(NativePortType port_) =>
      wasmModule.wire__crate__api_iroh__iroh_tunnel_port(port_);

  void wire__crate__api_iroh__iroh_tunnel_start(
    NativePortType port_,
    String endpoint_id,
    String relay_url,
    String relay_token,
  ) => wasmModule.wire__crate__api_iroh__iroh_tunnel_start(
    port_,
    endpoint_id,
    relay_url,
    relay_token,
  );

  void wire__crate__api_iroh__iroh_tunnel_stop(NativePortType port_) =>
      wasmModule.wire__crate__api_iroh__iroh_tunnel_stop(port_);

  void wire__crate__api_iroh__parse_iroh_pairing_uri(
    NativePortType port_,
    String uri,
  ) => wasmModule.wire__crate__api_iroh__parse_iroh_pairing_uri(port_, uri);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api_iroh__init_app(NativePortType port_);

  external void wire__crate__api_iroh__iroh_tunnel_path_status(
    NativePortType port_,
  );

  external void wire__crate__api_iroh__iroh_tunnel_port(NativePortType port_);

  external void wire__crate__api_iroh__iroh_tunnel_start(
    NativePortType port_,
    String endpoint_id,
    String relay_url,
    String relay_token,
  );

  external void wire__crate__api_iroh__iroh_tunnel_stop(NativePortType port_);

  external void wire__crate__api_iroh__parse_iroh_pairing_uri(
    NativePortType port_,
    String uri,
  );
}
